
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nysodi = { path = "../game", default-features = false }

[features]
default = ["nysodi/default"]
dylib-engine = ["nysodi/dylib-engine"]
